name: Trigger scheduled article publication
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  publish_scheduled:
    name: Trigger scheduled article publication
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: API request
        uses: fjogeleit/http-request-action@v1.9.1
        with:
          url: 'https://xpost.netlify.app/api/post/publish-scheduled'
          method: 'POST'
          bearerToken: ${{ secrets.SCHEDULED_KEY }}
