name: Trigger scheduled article publication
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  publish_scheduled:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Trigger scheduled article publication
        run: |
          curl --request POST \
          --url 'https://xpost.netlify.app/api/post/publish-scheduled' \
          --header 'Authorization: Bearer ${{ secrets.SCHEDULED_KEY }}'
